from datetime import datetime

from app.extensions import db


class CommandLog(db.Model):
    """Operations log table that records AI-generated district optimization summaries. Each record stores the timestamp, district name, raw optimization data in JSON format, and the LLM-generated textual summary for commanders."""
    __tablename__ = 'command_logs'

    id = db.Column(db.Integer, primary_key=True)
    timestamp = db.Column(db.DateTime, default=datetime.utcnow, index=True)
    district_name = db.Column(db.String(100), nullable=False, index=True)

    # Raw JSON data for debugging or displaying detailed data in the interface
    raw_json = db.Column(db.JSON, nullable=False)

    # Textual message generated by the LLM for the commander
    llm_summary_text = db.Column(db.Text, nullable=False)
